import type { MaterialSpec } from "./types";

/**
 * Canonical material specs mapped to calculator shopping-list line IDs.
 * Snapshot-backed prices live in observations.ts.
 */
export const MATERIAL_SPECS: MaterialSpec[] = [
  {
    id: "wood.post.pt.4x4.8.ground",
    calculatorLineIds: ["posts_buy"],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 4x4x8 post",
    nominalSize: "4x4 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.4x4.ground",
    allowance: { USD: 12, CAD: 14 },
  },
  {
    id: "wood.post.pt.4x4.10.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 4x4x10 post",
    nominalSize: "4x4 x 10 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.4x4.ground",
    allowance: { USD: 16, CAD: 18 },
  },
  {
    id: "wood.post.pt.4x4.12.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 4x4x12 post",
    nominalSize: "4x4 x 12 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.4x4.ground",
    allowance: { USD: 21, CAD: 22 },
  },
  {
    id: "wood.post.pt.4x4.14.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 4x4x14 post",
    nominalSize: "4x4 x 14 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.4x4.ground",
    allowance: { USD: 26, CAD: 28 },
  },
  {
    id: "wood.post.pt.4x4.16.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 4x4x16 post",
    nominalSize: "4x4 x 16 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.4x4.ground",
    allowance: { USD: 30, CAD: 32 },
  },
  {
    id: "wood.post.pt.6x6.8.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 6x6x8 post",
    nominalSize: "6x6 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.6x6.ground",
    allowance: { USD: 35, CAD: 28 },
  },
  {
    id: "wood.post.pt.6x6.10.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 6x6x10 post",
    nominalSize: "6x6 x 10 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.6x6.ground",
    allowance: { USD: 42, CAD: 35 },
  },
  {
    id: "wood.post.pt.6x6.12.ground",
    calculatorLineIds: [],
    category: "post",
    fenceSystem: "shared",
    name: "PT ground-contact 6x6x12 post",
    nominalSize: "6x6 x 12 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "post.6x6.ground",
    allowance: { USD: 50, CAD: 42 },
  },
  {
    id: "wood.bracket.structure",
    calculatorLineIds: ["posts_structure"],
    category: "hardware",
    fenceSystem: "shared",
    name: "Wall / structure connection bracket",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 6, CAD: 5.5 },
  },
  {
    id: "wood.panel.pt.6x8.privacy",
    calculatorLineIds: ["panels_buy"],
    calculatorLinePrefixes: ["panels_cut_"],
    category: "panel",
    fenceSystem: "panel",
    name: "PT 6x8 privacy panel",
    nominalSize: "6 ft x 8 ft",
    baseUnit: "panel",
    packageQuantity: 1,
    substitutionGroup: "panel.6x8.privacy",
    allowance: { USD: 75, CAD: 130 },
  },
  {
    id: "wood.rail.pt.2x4.8",
    calculatorLineIds: ["rails"],
    category: "rail",
    fenceSystem: "wood",
    name: "PT 2x4x8 rail / stringer",
    nominalSize: "2x4 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "rail.2x4.8",
    allowance: { USD: 5, CAD: 10 },
  },
  {
    id: "wood.picket.pt.1x6.6",
    calculatorLineIds: ["pickets"],
    category: "picket",
    fenceSystem: "wood",
    name: "PT 1x6x6 fence board / picket",
    nominalSize: "1x6 x 6 ft",
    baseUnit: "each",
    packageQuantity: 1,
    substitutionGroup: "picket.1x6.6",
    allowance: { USD: 2.5, CAD: 3.5 },
  },
  {
    id: "wood.batten.pt.2x2.8",
    calculatorLineIds: ["battens"],
    category: "picket",
    fenceSystem: "wood",
    name: "PT 2x2x8 batten",
    nominalSize: "2x2 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 5, CAD: 7 },
  },
  {
    id: "wire.panel.welded.6x50",
    calculatorLineIds: ["wire_panels"],
    category: "fabric",
    fenceSystem: "wood",
    name: "Galvanized welded wire 6 ft x 50 ft",
    baseUnit: "roll",
    packageQuantity: 1,
    allowance: { USD: 95, CAD: 108 },
  },
  {
    id: "cl.fabric.galv.6x50",
    calculatorLineIds: ["fabric"],
    category: "fabric",
    fenceSystem: "chain_link",
    name: "Galvanized chain-link fabric 6 ft x 50 ft",
    baseUnit: "roll",
    packageQuantity: 1,
    substitutionGroup: "cl.fabric.6x50",
    allowance: { USD: 149, CAD: 300 },
  },
  {
    id: "cl.rail.137.10",
    calculatorLineIds: ["top_rail"],
    category: "rail",
    fenceSystem: "chain_link",
    name: "Chain-link top rail ~1-3/8 in x 10 ft",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 25, CAD: 24 },
  },
  {
    id: "cl.ties.50pack",
    calculatorLineIds: ["ties"],
    category: "hardware",
    fenceSystem: "chain_link",
    name: "Chain-link fence ties",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 0.2, CAD: 0.18 },
  },
  {
    id: "cl.tension_bar",
    calculatorLineIds: ["tension_bars"],
    category: "hardware",
    fenceSystem: "chain_link",
    name: "Tension bar",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 4, CAD: 4.6 },
  },
  {
    id: "cl.brace_band",
    calculatorLineIds: ["brace_bands"],
    category: "hardware",
    fenceSystem: "chain_link",
    name: "Brace / tension band",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 1.2, CAD: 1 },
  },
  {
    id: "concrete.bag.standard",
    calculatorLineIds: ["concrete"],
    category: "concrete",
    fenceSystem: "shared",
    name: "Concrete mix bag (post hole)",
    baseUnit: "bag",
    packageQuantity: 1,
    substitutionGroup: "concrete.bag",
    allowance: { USD: 7, CAD: 12 },
  },
  {
    id: "gate.kit.basic",
    calculatorLineIds: ["hinges", "latches"],
    category: "gate hardware",
    fenceSystem: "shared",
    name: "Basic hinge-and-latch gate kit (allocated per set)",
    baseUnit: "kit",
    packageQuantity: 1,
    allowance: { USD: 25, CAD: 22 },
  },
  {
    id: "gate.drop_rod.36",
    calculatorLineIds: ["drop_rods"],
    category: "gate hardware",
    fenceSystem: "shared",
    name: "36 in drop rod",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 22, CAD: 26 },
  },
  {
    id: "wood.post_cap.flat",
    calculatorLineIds: ["post_caps"],
    category: "accessory",
    fenceSystem: "shared",
    name: "Basic 4x4 post cap",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 5, CAD: 6 },
  },
  {
    id: "wood.trim.pt.1x4.8",
    calculatorLineIds: ["picture_frame", "cap_trim"],
    category: "accessory",
    fenceSystem: "wood",
    name: "PT 1x4x8 trim",
    nominalSize: "1x4 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 3, CAD: 3 },
  },
  {
    id: "wood.cap.pt.2x6.8",
    calculatorLineIds: ["cap_rail", "kickboard"],
    category: "accessory",
    fenceSystem: "wood",
    name: "PT 2x6x8 cap / kickboard",
    nominalSize: "2x6 x 8 ft",
    baseUnit: "each",
    packageQuantity: 1,
    allowance: { USD: 12, CAD: 18 },
  },
  {
    id: "wood.lattice.pt.4x8",
    calculatorLineIds: ["lattice"],
    category: "accessory",
    fenceSystem: "wood",
    name: "PT 4x8 lattice sheet",
    baseUnit: "panel",
    packageQuantity: 1,
    allowance: { USD: 22, CAD: 20 },
  },
  {
    id: "fastener.screw.2in",
    calculatorLineIds: ["screws_boards"],
    category: "fastener",
    fenceSystem: "shared",
    name: "2 in exterior deck screws",
    baseUnit: "box",
    packageQuantity: 500,
    packageSizes: [100, 500, 2500],
    pricePerPackage: true,
    allowance: { USD: 33, CAD: 36 },
  },
  {
    id: "fastener.screw.3in",
    calculatorLineIds: ["screws_rails", "screws_brackets", "screws_gates"],
    category: "fastener",
    fenceSystem: "shared",
    name: "3 in exterior deck screws",
    baseUnit: "box",
    packageQuantity: 500,
    packageSizes: [100, 500, 1000, 2500],
    pricePerPackage: true,
    allowance: { USD: 36, CAD: 40 },
  },
  {
    id: "fastener.screw.2_5in",
    calculatorLineIds: ["screws_trim"],
    category: "fastener",
    fenceSystem: "shared",
    name: "2-1/2 in exterior deck screws",
    baseUnit: "box",
    packageQuantity: 850,
    packageSizes: [100, 850, 1200, 2500],
    pricePerPackage: true,
    allowance: { USD: 40, CAD: 53 },
  },
  {
    id: "fastener.staple.galv",
    calculatorLineIds: ["staples_wire"],
    category: "fastener",
    fenceSystem: "wood",
    name: "Galvanized fencing staples (pack)",
    baseUnit: "box",
    packageQuantity: 80,
    packageSizes: [80],
    pricePerPackage: true,
    allowance: { USD: 12, CAD: 13 },
  },
  {
    id: "hardware.panel_bracket",
    calculatorLineIds: ["panel_brackets"],
    category: "hardware",
    fenceSystem: "panel",
    name: "Fence panel mounting brackets (multi-pack)",
    baseUnit: "box",
    packageQuantity: 3,
    packageSizes: [3],
    pricePerPackage: true,
    allowance: { USD: 12, CAD: 19 },
  },
  {
    id: "hardware.misc.kit",
    calculatorLineIds: ["fasteners_misc", "fasteners"],
    category: "fastener",
    fenceSystem: "shared",
    name: "Misc fasteners / hardware kit",
    baseUnit: "kit",
    packageQuantity: 1,
    allowance: { USD: 15, CAD: 18 },
  },
];

export function findSpecById(specId: string): MaterialSpec | undefined {
  return MATERIAL_SPECS.find((s) => s.id === specId);
}

export function findSpecForLineId(lineId: string): MaterialSpec | undefined {
  const exact = MATERIAL_SPECS.find((s) =>
    s.calculatorLineIds.includes(lineId),
  );
  if (exact) return exact;
  return MATERIAL_SPECS.find((s) =>
    (s.calculatorLinePrefixes ?? []).some((p) => lineId.startsWith(p)),
  );
}

/** Prefer an explicit pricingSpecId (length/face-specific posts), else line id. */
export function findSpecForMaterialLine(line: {
  id: string;
  pricingSpecId?: string;
}): MaterialSpec | undefined {
  if (line.pricingSpecId) {
    const byId = findSpecById(line.pricingSpecId);
    if (byId) return byId;
  }
  return findSpecForLineId(line.id);
}

/** Stable pricing catalog id for a retail post size. */
export function postPricingSpecId(
  face: "4x4" | "6x6",
  lengthFt: number,
): string {
  const common = [6, 8, 10, 12, 14, 16];
  const len = common.includes(lengthFt)
    ? lengthFt
    : common.find((c) => c >= lengthFt) ?? 16;
  return `wood.post.pt.${face}.${len}.ground`;
}
