import type { PriceObservation } from "./types";

/** Starter market snapshot — 2026-07-19 (see docs/FENCE_MATERIAL_PRICING_DATABASE.md). */
export const SNAPSHOT_AS_OF = "2026-07-19";

/** Bank of Canada business-day rate used for converted CA fallbacks. */
export const USD_TO_CAD_RATE = 1.4014;
export const USD_TO_CAD_RATE_DATE = "2026-07-17";

export const PRICE_OBSERVATIONS: PriceObservation[] = [
  // ——— United States (USD) ———
  {
    id: "us-hd-post-4x4x8",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    region: "South",
    currency: "USD",
    regularPrice: 10.48,
    bulkPrice: 9.43,
    bulkMinQuantity: 78,
    normalizedUnitPrice: 10.48,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-lowes-post-4x4x8-houston",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    region: "South",
    currency: "USD",
    regularPrice: 10.48,
    normalizedUnitPrice: 10.48,
    stockStatus: "in_stock",
    retailer: "Lowe's",
    title: "Houston PT 4x4 family",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-lowes-post-4x4x8-indy",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    region: "Midwest",
    currency: "USD",
    regularPrice: 11.28,
    normalizedUnitPrice: 11.28,
    stockStatus: "in_stock",
    retailer: "Lowe's",
    title: "Indianapolis PT 4x4 family",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-lowes-post-4x4x8-anaheim",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    region: "Pacific",
    currency: "USD",
    regularPrice: 17.68,
    normalizedUnitPrice: 17.68,
    stockStatus: "in_stock",
    retailer: "Lowe's",
    title: "Anaheim hem-fir example",
    collectionMethod: "manual",
    confidence: "medium",
    isSubstitute: true,
    substituteNote: "Hem-fir / regional species variant",
  },
  {
    id: "us-hd-post-4x4x10",
    materialSpecId: "wood.post.pt.4x4.10.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 15.98,
    bulkPrice: 14.38,
    bulkMinQuantity: 78,
    normalizedUnitPrice: 15.98,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "PT ground-contact 4x4x10",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-post-4x4x12",
    materialSpecId: "wood.post.pt.4x4.12.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 20.97,
    normalizedUnitPrice: 20.97,
    stockStatus: "in_stock",
    retailer: "Home Depot / regional lumber",
    title: "PT ground-contact 4x4x12 (indicative retail)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-mccoys-post-4x4x12",
    materialSpecId: "wood.post.pt.4x4.12.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 21.99,
    normalizedUnitPrice: 21.99,
    stockStatus: "in_stock",
    retailer: "McCoy's",
    title: "4x4x12 waxed ground-contact treated pine",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-post-6x6x8",
    materialSpecId: "wood.post.pt.6x6.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 34.68,
    bulkPrice: 31.21,
    normalizedUnitPrice: 34.68,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-rail-2x4x8",
    materialSpecId: "wood.rail.pt.2x4.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 4.68,
    bulkPrice: 4.21,
    normalizedUnitPrice: 4.68,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-picket-1x6x6",
    materialSpecId: "wood.picket.pt.1x6.6",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 2.18,
    bulkPrice: 1.96,
    normalizedUnitPrice: 2.18,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-panel-6x8",
    materialSpecId: "wood.panel.pt.6x8.privacy",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 73.98,
    normalizedUnitPrice: 73.98,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-concrete-80",
    materialSpecId: "concrete.bag.standard",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 6.47,
    normalizedUnitPrice: 6.47,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "QUIKRETE 80 lb concrete mix",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-screw-2in-deckmate",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 32.98,
    normalizedUnitPrice: 32.98,
    piecesPerPackage: 453,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "DECKMATE #8 x 2 in exterior deck screws 5 lb / ~453",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-screw-2in-griprite",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 29.97,
    normalizedUnitPrice: 29.97,
    piecesPerPackage: 500,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "Grip-Rite #8 x 2 in coated exterior screws 5 lb box",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-screw-2in-camo-bulk",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 98.38,
    normalizedUnitPrice: 98.38,
    piecesPerPackage: 1750,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "CAMO #8 x 2 in exterior deck screws 1750-count",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-screw-3in-100",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 12.97,
    normalizedUnitPrice: 12.97,
    piecesPerPackage: 100,
    stockStatus: "catalog",
    retailer: "Home Depot",
    title: "3 in exterior deck screws ~100-ct box (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-screw-3in-500",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 34.97,
    normalizedUnitPrice: 34.97,
    piecesPerPackage: 500,
    stockStatus: "catalog",
    retailer: "Home Depot",
    title: "3 in exterior deck screws ~500-ct box (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-screw-3in-1000",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 54.97,
    normalizedUnitPrice: 54.97,
    piecesPerPackage: 1000,
    stockStatus: "catalog",
    retailer: "Home Depot",
    title: "3 in exterior deck screws ~1000-ct box (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-screw-2_5in-100",
    materialSpecId: "fastener.screw.2_5in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 11.97,
    normalizedUnitPrice: 11.97,
    piecesPerPackage: 100,
    stockStatus: "catalog",
    retailer: "Home Depot",
    title: "2-1/2 in exterior deck screws ~100-ct (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-screw-2_5in",
    materialSpecId: "fastener.screw.2_5in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 49.97,
    normalizedUnitPrice: 49.97,
    piecesPerPackage: 850,
    stockStatus: "catalog",
    retailer: "Home Depot",
    title: "2-1/2 in exterior deck screws ~850-ct box (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-gate-kit",
    materialSpecId: "gate.kit.basic",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 29.98,
    normalizedUnitPrice: 14.99,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    title: "Gate kit allocated per hinge or latch set",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "us-hd-fabric-6x50",
    materialSpecId: "cl.fabric.galv.6x50",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 149,
    normalizedUnitPrice: 149,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "us-hd-top-rail",
    materialSpecId: "cl.rail.137.10",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "US",
    currency: "USD",
    regularPrice: 24.97,
    bulkPrice: 22.47,
    normalizedUnitPrice: 24.97,
    stockStatus: "in_stock",
    retailer: "Home Depot",
    collectionMethod: "manual",
    confidence: "high",
  },

  // ——— Canada (CAD) ———
  {
    id: "ca-hd-post-4x4x8",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    region: "Ontario",
    currency: "CAD",
    regularPrice: 9.2,
    bulkPrice: 8.28,
    bulkMinQuantity: 78,
    normalizedUnitPrice: 9.2,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-rona-post-4x4x8",
    materialSpecId: "wood.post.pt.4x4.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    region: "Quebec",
    currency: "CAD",
    regularPrice: 16.25,
    normalizedUnitPrice: 16.25,
    stockStatus: "in_stock",
    retailer: "RONA",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-post-4x4x10",
    materialSpecId: "wood.post.pt.4x4.10.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 11.53,
    bulkPrice: 10.38,
    bulkMinQuantity: 78,
    normalizedUnitPrice: 11.53,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "PT ground-contact 4x4x10",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-lumber-post-4x4x10",
    materialSpecId: "wood.post.pt.4x4.10.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 20.5,
    normalizedUnitPrice: 20.5,
    stockStatus: "catalog",
    retailer: "Independent lumber (scaled)",
    title: "4x4x10 ground-contact — yard-level vs big-box spread",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-post-4x4x12",
    materialSpecId: "wood.post.pt.4x4.12.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 14.26,
    bulkPrice: 12.83,
    bulkMinQuantity: 78,
    normalizedUnitPrice: 14.26,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "PT ground-contact 4x4x12",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-timbermart-post-4x4x12",
    materialSpecId: "wood.post.pt.4x4.12.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    region: "Ontario",
    currency: "CAD",
    regularPrice: 25.08,
    normalizedUnitPrice: 25.08,
    stockStatus: "in_stock",
    retailer: "Chamberlain Timber Mart",
    title: "4x4x12 MicroPro Sienna PT",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-post-6x6x8",
    materialSpecId: "wood.post.pt.6x6.8.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 25.97,
    bulkPrice: 23.37,
    normalizedUnitPrice: 25.97,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-post-6x6x10",
    materialSpecId: "wood.post.pt.6x6.10.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 33.2,
    bulkPrice: 29.88,
    normalizedUnitPrice: 33.2,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-post-6x6x12",
    materialSpecId: "wood.post.pt.6x6.12.ground",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 39.34,
    bulkPrice: 35.41,
    normalizedUnitPrice: 39.34,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-rail-2x4x8",
    materialSpecId: "wood.rail.pt.2x4.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 11.2,
    normalizedUnitPrice: 11.2,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-rona-rail-2x4x8",
    materialSpecId: "wood.rail.pt.2x4.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 6.98,
    normalizedUnitPrice: 6.98,
    stockStatus: "in_stock",
    retailer: "RONA",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-picket-1x6x6",
    materialSpecId: "wood.picket.pt.1x6.6",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 2.68,
    normalizedUnitPrice: 2.68,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-rona-picket-1x6x6",
    materialSpecId: "wood.picket.pt.1x6.6",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 3.98,
    normalizedUnitPrice: 3.98,
    stockStatus: "in_stock",
    retailer: "RONA",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-panel-6x8",
    materialSpecId: "wood.panel.pt.6x8.privacy",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 129,
    normalizedUnitPrice: 129,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-concrete-fnp",
    materialSpecId: "concrete.bag.standard",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 11.76,
    normalizedUnitPrice: 11.76,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "QUIKRETE Fence N' Post 30 kg",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-2in-500",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 36,
    normalizedUnitPrice: 36,
    piecesPerPackage: 500,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "2 in exterior deck screws 500-ct box (DIY pack)",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-2in-2500",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 95,
    normalizedUnitPrice: 95,
    piecesPerPackage: 2500,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "2 in exterior deck screws 2500-ct contractor box",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-2in-100",
    materialSpecId: "fastener.screw.2in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 13.78,
    normalizedUnitPrice: 13.78,
    piecesPerPackage: 100,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "Paulin #8 x 2 in deck screws 100-ct",
    sourceUrl:
      "https://www.homedepot.ca/product/paulin--8-x-2-inch-square-drive-flat-head-deck-screw-unc-in-brown-100pcs/1000110580",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-2_5in-850",
    materialSpecId: "fastener.screw.2_5in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 52.98,
    normalizedUnitPrice: 52.98,
    piecesPerPackage: 850,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "PaulinPRO #8 x 2-1/2 in deck screws 850-ct",
    sourceUrl:
      "https://www.homedepot.ca/product/paulinpro-pro-8-x-2-1-2-inch-deck-screws-in-brown-850-pack/1001109916",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-3in-100",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 17.98,
    normalizedUnitPrice: 17.98,
    piecesPerPackage: 100,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "Paulin #8 x 3 in deck screws 100-ct",
    sourceUrl:
      "https://www.homedepot.ca/product/paulin--8-x-3-inch-square-drive-flat-head-deck-screw-unc-in-brown-100pcs/1000111387",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-3in-500",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 39.98,
    normalizedUnitPrice: 39.98,
    piecesPerPackage: 500,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    title: "3 in exterior deck screws 500-ct (indicative mid pack)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-screw-3in-1000",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 52.98,
    normalizedUnitPrice: 52.98,
    piecesPerPackage: 1000,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "Paulin #8 x 3 in deck screws 1000-ct",
    sourceUrl:
      "https://www.homedepot.ca/product/paulin--8-x-3-inch-square-drive-flat-head-deck-screw-unc-in-brown-1000pcs/1000152763",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-screw-3in-2500",
    materialSpecId: "fastener.screw.3in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 95,
    normalizedUnitPrice: 95,
    piecesPerPackage: 2500,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    title: "3 in exterior deck screws 2500-ct contractor box (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-screw-2_5in-100",
    materialSpecId: "fastener.screw.2_5in",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 16.98,
    normalizedUnitPrice: 16.98,
    piecesPerPackage: 100,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    title: "2-1/2 in exterior deck screws 100-ct (indicative)",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-gate-kit",
    materialSpecId: "gate.kit.basic",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 21.98,
    normalizedUnitPrice: 10.99,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "Traditional hinge-and-latch kit / 2 sets",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-drop-rod",
    materialSpecId: "gate.drop_rod.36",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 25.94,
    normalizedUnitPrice: 25.94,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-post-cap",
    materialSpecId: "wood.post_cap.flat",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 5.99,
    normalizedUnitPrice: 5.99,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-trim-1x4",
    materialSpecId: "wood.trim.pt.1x4.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 2.88,
    normalizedUnitPrice: 2.88,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-cap-2x6",
    materialSpecId: "wood.cap.pt.2x6.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 17.21,
    normalizedUnitPrice: 17.21,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-lattice",
    materialSpecId: "wood.lattice.pt.4x8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 19.2,
    normalizedUnitPrice: 19.2,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-batten",
    materialSpecId: "wood.batten.pt.2x2.8",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 6.87,
    normalizedUnitPrice: 6.87,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "low",
    isSubstitute: true,
    substituteNote: "2x2 proxy for 1x2 / 1x3 battens",
  },
  {
    id: "ca-hd-wire-panel",
    materialSpecId: "wire.panel.welded.6x50",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 108,
    normalizedUnitPrice: 108,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-fabric-6x50",
    materialSpecId: "cl.fabric.galv.6x50",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 371.07,
    normalizedUnitPrice: 371.07,
    stockStatus: "orderable",
    retailer: "ALEKO Canada",
    title: "6x50 12.5 ga substitute",
    collectionMethod: "manual",
    confidence: "medium",
    isSubstitute: true,
    substituteNote: "12.5 ga Canadian supplier example — not exact 11.5 ga match",
  },
  {
    id: "ca-hd-top-rail",
    materialSpecId: "cl.rail.137.10",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 23.75,
    normalizedUnitPrice: 23.75,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-ties",
    materialSpecId: "cl.ties.50pack",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 8.7,
    normalizedUnitPrice: 0.174,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "50-pack ties",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-tension-bar",
    materialSpecId: "cl.tension_bar",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 4.6,
    normalizedUnitPrice: 4.6,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "58 in tension bar",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-brace-band",
    materialSpecId: "cl.brace_band",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 0.98,
    normalizedUnitPrice: 0.98,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    collectionMethod: "manual",
    confidence: "low",
    isSubstitute: true,
    substituteNote: "Approximate band substitute",
  },
  {
    id: "ca-hd-panel-bracket",
    materialSpecId: "hardware.panel_bracket",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 18.69,
    normalizedUnitPrice: 18.69,
    piecesPerPackage: 3,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "Universal panel brackets 3-pack",
    collectionMethod: "manual",
    confidence: "high",
  },
  {
    id: "ca-hd-staple",
    materialSpecId: "fastener.staple.galv",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 12.98,
    normalizedUnitPrice: 12.98,
    piecesPerPackage: 80,
    stockStatus: "in_stock",
    retailer: "Home Depot Canada",
    title: "~80 staples / pack",
    collectionMethod: "manual",
    confidence: "medium",
  },
  {
    id: "ca-hd-structure-bracket",
    materialSpecId: "wood.bracket.structure",
    observedAt: `${SNAPSHOT_AS_OF}T12:00:00Z`,
    country: "CA",
    currency: "CAD",
    regularPrice: 15.39,
    normalizedUnitPrice: 5.13,
    stockStatus: "catalog",
    retailer: "Home Depot Canada",
    title: "Wall bracket 3-pack",
    collectionMethod: "manual",
    confidence: "medium",
  },
];
